from abc import ABC, abstractmethod
from typing import AsyncIterator, List, Dict, Any
from datetime import datetime
from .models import MarketEvent, SemanticEvent, Hypothesis, LayerOutput

class BaseProvider(ABC):
    @abstractmethod
    async def connect(self): ...
    @abstractmethod
    async def disconnect(self): ...
    @abstractmethod
    async def get_candles(self, symbol: str, start: datetime, end: datetime) -> AsyncIterator[MarketEvent]: ...
    @abstractmethod
    async def health(self) -> bool: ...

class EventBus(ABC):
    @abstractmethod
    async def publish(self, topic: str, event: BaseModel): ...
    @abstractmethod
    async def subscribe(self, topic: str) -> AsyncIterator: ...

class Detector(ABC):
    @abstractmethod
    def required_concepts(self) -> List[str]: ...
    @abstractmethod
    async def detect(self, events: List[MarketEvent]) -> List[SemanticEvent]: ...

class MotorICT(ABC):
    """Interface que todo motor ICT deve implementar."""
    @abstractmethod
    def analyze(self, context: Dict[str, Any]) -> LayerOutput: ...
    @abstractmethod
    def validate(self, output: LayerOutput) -> bool: ...
    @abstractmethod
    def explain(self, output: LayerOutput) -> List[str]: ...
    @abstractmethod
    def metrics(self) -> Dict[str, float]: ...
    @abstractmethod
    def audit(self, output: LayerOutput) -> Dict[str, Any]: ...

class InferenceEngine(ABC):
    @abstractmethod
    async def infer(self, semantic_events: List[SemanticEvent], market_events: List[MarketEvent]) -> List[Hypothesis]: ...
